 export let keyValue = [
{charCode: 96, code: 'Backquote', key: '`', keyCode: 96},
{charCode: 49, code: 'Digit1', key: '1', keyCode: 49},
{charCode: 50, code: 'Digit2', key: '2', keyCode: 50},
{charCode: 51, code: 'Digit3', key: '3', keyCode: 51},
{charCode: 52, code: 'Digit4', key: '4', keyCode: 52},
{charCode: 53, code: 'Digit5', key: '5', keyCode: 53},
{charCode: 54, code: 'Digit6', key: '6', keyCode: 54},
{charCode: 55, code: 'Digit7', key: '7', keyCode: 55},
{charCode: 56, code: 'Digit8', key: '8', keyCode: 56},
{charCode: 57, code: 'Digit9', key: '9', keyCode: 57},
{charCode: 48, code: 'Digit0', key: '0', keyCode: 48},
{charCode: 45, code: 'Minus', key: '-', keyCode: 45},
{charCode: 61, code: 'Equal', key: '=', keyCode: 61},
{key:'Backspace', code:'Backspace'},
{key:'Tab',code:'Tab',},
{charCode: 113, code: 'KeyQ', key: 'q', keyCode: 113},
{charCode: 119, code: 'KeyW', key: 'w', keyCode: 119},
{charCode: 101, code: 'KeyE', key: 'e', keyCode: 101},
{charCode: 114, code: 'KeyR', key: 'r', keyCode: 114},
{charCode: 116, code: 'KeyT', key: 't', keyCode: 116},
{charCode: 121, code: 'KeyY', key: 'y', keyCode: 121},
{charCode: 117, code: 'KeyU', key: 'u', keyCode: 117},
{charCode: 105, code: 'KeyI', key: 'i', keyCode: 105},
{charCode: 111, code: 'KeyO', key: 'o', keyCode: 111},
{charCode: 112, code: 'KeyP', key: 'p', keyCode: 112},
{charCode: 91, code: 'BracketLeft', key: '[', keyCode: 91},
{charCode: 93, code: 'BracketRight', key: ']', keyCode: 93},
{charCode: 92, code: 'Backslash', key: '\\', keyCode: 92},
{key:'Delete', code:'Delete',},
{key:'CapsLock', code:'CapsLock',},
{charCode: 97, code: 'KeyA', key: 'a', keyCode: 97},
{charCode: 115, code: 'KeyS', key: 's', keyCode: 115},
{charCode: 100, code: 'KeyD', key: 'd', keyCode: 100},
{charCode: 102, code: 'KeyF', key: 'f', keyCode: 102},
{charCode: 103, code: 'KeyG', key: 'g', keyCode: 103},
{charCode: 104, code: 'KeyH', key: 'h', keyCode: 104},
{charCode: 106, code: 'KeyJ', key: 'j', keyCode: 106},
{charCode: 107, code: 'KeyK', key: 'k', keyCode: 107},
{charCode: 108, code: 'KeyL', key: 'l', keyCode: 108},
{charCode: 59, code: 'Semicolon', key: ';', keyCode: 59},
{charCode: 39, code: 'Quote', key: "'", keyCode: 39},
{charCode: 13, code: 'Enter', key: 'Enter', keyCode: 13},
{key:'Shift', code:"ShiftLefT"},
{charCode: 122, code: 'KeyZ', key: 'z', keyCode: 122},
{charCode: 120, code: 'KeyX', key: 'x', keyCode: 120},
{charCode: 99, code: 'KeyC', key: 'c', keyCode: 99},
{charCode: 118, code: 'KeyV', key: 'v', keyCode: 118},
{charCode: 98, code: 'KeyB', key: 'b', keyCode: 98},
{charCode: 110, code: 'KeyN', key: 'n', keyCode: 110},
{charCode: 109, code: 'KeyM', key: 'm', keyCode: 109},
{charCode: 44, code: 'Comma', key: ',', keyCode: 44},
{charCode: 46, code: 'Period', key: '.', keyCode: 46},
{charCode: 47, code: 'Slash', key: '/', keyCode: 47},
{key:'Shift', code:'ShiftRight'},
{key: '&uarr;', code:'ArrowTop'},
{key:'Control', code:'ControlLeft'},
{key:'Meta', code: 'MetaLeft'},
{key:'Alt', code:'AltLeft'},
{charCode: 32, code: 'Space', key: ' ', keyCode: 32},
{key:'Alt', code:'AltRight'},
{key:'Control', code:'ControlRight'},
{key:'&larr;', code:'ArrowLeft'},
{key: '&darr;', code:'ArrowBottom'},
{key:'&rarr;', code:'ArrowRight'},
]
export const keyValueRus = [
	{charCode: 49, code: 'Digit1', key: '1', keyCode: 49},
	{charCode: 50, code: 'Digit2', key: '2', keyCode: 50},
	{charCode: 51, code: 'Digit3', key: '3', keyCode: 51},
	{charCode: 52, code: 'Digit4', key: '4', keyCode: 52},
	{charCode: 53, code: 'Digit5', key: '5', keyCode: 53},
	{charCode: 54, code: 'Digit6', key: '6', keyCode: 54},
	{charCode: 55, code: 'Digit7', key: '7', keyCode: 55},
	{charCode: 56, code: 'Digit8', key: '8', keyCode: 56},
	{charCode: 57, code: 'Digit9', key: '9', keyCode: 57},
	{charCode: 48, code: 'Digit0', key: '0', keyCode: 48},
	{charCode: 45, code: 'Minus', key: '-', keyCode: 45},
	{charCode: 61, code: 'Equal', key: '=', keyCode: 61},
	{key:'Backspace', code:'Backspace'},
  {key:'Tab',code:'Tab',},
	{charCode: 1081, code: 'KeyQ', key: 'й', keyCode: 1081},
	{charCode: 1081, code: 'KeyQ', key: 'й', keyCode: 1081},
	{charCode: 1094, code: 'KeyW', key: 'ц', keyCode: 1094},
	{charCode: 1091, code: 'KeyE', key: 'у', keyCode: 1091},
	{charCode: 1082, code: 'KeyR', key: 'к', keyCode: 1082},
	{charCode: 1077, code: 'KeyT', key: 'е', keyCode: 1077},
	{charCode: 1085, code: 'KeyY', key: 'н', keyCode: 1085},
	{charCode: 1075, code: 'KeyU', key: 'г', keyCode: 1075},
	{charCode: 1096, code: 'KeyI', key: 'ш', keyCode: 1096},
	{charCode: 1097, code: 'KeyO', key: 'щ', keyCode: 1097},
	{charCode: 1079, code: 'KeyP', key: 'з', keyCode: 1079},
	{charCode: 1093, code: 'BracketLeft', key: 'х', keyCode: 1093},
	{charCode: 1098, code: 'BracketRight', key: 'ъ', keyCode: 1098},
	{charCode: 92, code: 'Backslash', key: '\\', keyCode: 92},
	{key:'Delete', code:'Delete',},
  {key:'CapsLock', code:'CapsLock',},
	{charCode: 1092, code: 'KeyA', key: 'ф', keyCode: 1092},
	{charCode: 1099, code: 'KeyS', key: 'ы', keyCode: 1099},
	{charCode: 1074, code: 'KeyD', key: 'в', keyCode: 1074},
	{charCode: 1072, code: 'KeyF', key: 'а', keyCode: 1072},
	{charCode: 1087, code: 'KeyG', key: 'п', keyCode: 1087},
	{charCode: 1088, code: 'KeyH', key: 'р', keyCode: 1088},
	{charCode: 1086, code: 'KeyJ', key: 'о', keyCode: 1086},
	{charCode: 1083, code: 'KeyK', key: 'л', keyCode: 1083},
	{charCode: 1076, code: 'KeyL', key: 'д', keyCode: 1076},
	{charCode: 1078, code: 'Semicolon', key: 'ж', keyCode: 1078},
	{charCode: 1101, code: 'Quote', key: 'э', keyCode: 1101},
	{charCode: 13, code: 'Enter', key: 'Enter', keyCode: 13},
  {key:'Shift', code:"ShiftLefT"},
	{charCode: 1103, code: 'KeyZ', key: 'я', keyCode: 1103},
	{charCode: 1095, code: 'KeyX', key: 'ч', keyCode: 1095},
	{charCode: 1089, code: 'KeyC', key: 'с', keyCode: 1089},
	{charCode: 1084, code: 'KeyV', key: 'м', keyCode: 1084},
	{charCode: 1080, code: 'KeyB', key: 'и', keyCode: 1080},
	{charCode: 1090, code: 'KeyN', key: 'т', keyCode: 1090},
	{charCode: 1100, code: 'KeyM', key: 'ь', keyCode: 1100},
	{charCode: 1073, code: 'Comma', key: 'б', keyCode: 1073},
	{charCode: 1102, code: 'Period', key: 'ю', keyCode: 1102},
	{charCode: 46, code: 'Slash', key: '.', keyCode: 46},
	{key:'Shift', code:'ShiftRigh'},
	{key: '&uarr;', code:'ArrowTop'},
	{key:'Control', code:'ControlLeft'},
	{key:'Meta', code: 'MetaLeft'},
	{key:'Alt', code:'AltLeft'},
	{charCode: 32, code: 'Space', key: ' ', keyCode: 32},
	{key:'Alt', code:'AltRight'},
	{key:'Control', code:'ControlRight'},
	{key:'&larr;', code:'ArrowLeft'},
	{key: '&darr;', code:'ArrowBottom'},
	{key:'&rarr;', code:'ArrowRight'},
	]



	document.addEventListener('keypress', (e)=>{
		let obj = {
	charCode: null,//-------------------
	code: "",//------------------
	// composed: true,
	// ctrlKey: false,
	// currentTarget: null,
	// defaultPrevented: false,
	// detail: 0,
	// eventPhase: 0,
	// isComposing: false,
	key: "",//------------------------
	keyCode: null,//--------------------
	// location: 0,
	// metaKey: false,
	// repeat: false,
	// returnValue: true,
	// shiftKey: false,
	}
	
	
	if(e){
		obj.key = e.key,
		obj.keyCode = e.keyCode,
		obj.charCode = e.charCode,
		obj.code = e.code,
		//keyValue.push(obj)
		keyValueRus.push(obj)
	}
		
	if(e.shiftKey){
		obj.key = e.key,
		obj.keyCode = e.keyCode,
		obj.charCode = e.charCode,
		obj.code = e.code,
		keyValueRus.push(obj)
		console.log(e)
	
	}
	
	
	})
